### ISSUE TITLE
Research Apis

### ISSUE THREAD

**Issue by nicholaswbowen** [Kamillionaire/Hoodfacts#1]
What public apis are available for the following:
 1. Rent Prices
 2. School Districts
 3. Crime Rates 
 4. Age range
 5. Food ratings 
 6. Avg internet speed

**Comment by nicholaswbowen** [comment]
timed requests: how often do these apis update?
caching data legality: Are we allowed to cache the data?

**Comment by nicholaswbowen** [comment]
We need to have a set algorithm that can take in different types of location data and transform it into a standard location type that app uses. For example, some apis may have their locations in traditional degrees as opposed to decimal location . Or if a database lists data by county without a lat/long, we may need to cross-reference it with a database that has those county's locations.

**Comment by nicholaswbowen** [comment]
Additional apis: 
7. Political Parties (I'd really like to do this one)
8. Median Wealth
9. Stuff people don't want to talk about. (addiction, overdoses, suicides)

**Comment by JacobOMiller** [comment]
https://spotcrime.com/ | https://github.com/contra/spotcrime | http://stackoverflow.com/questions/10123933/api-for-address-school-district-lookup | https://support.google.com/fusiontables/answer/1182141?hl=en | https://blog.quandl.com/api-for-housing-data | http://developer.zoopla.com/ | http://www.zilpy.com/api
