### ISSUE TITLE
Server side Boilerplate

### ISSUE THREAD

**Issue by Kamillionaire** [Kamillionaire/Hoodfacts#5]

**Comment by nicholaswbowen** [comment]
Mongoose Models for : 
User

**Comment by nicholaswbowen** [comment]
Server one: 
Crawler/cache bot
1. Collect and cache data from twitter places for geometric boundaries at specific intervals.
2. Cache data from a variety of sources at specific intervals
3. Add cleaned/decorated data to the database
4. If a client requests data that is unavailable in the cache, go fetch it. 
Server two: 
1. Provide apis
2. Auth
3. general web server tasks.
